config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/songs', to: 'songs#index'
  get '/songs/:id', to: 'songs#show'

  # get '/artists', to: 'artists#index'
  # get '/artists/new', to: 'artists#new'
  # post '/artists', to: 'artists#create'
  # delete '/artists/:id', to: 'artists#destroy'
  # get '/artists/:id/edit', to: 'artists#edit'
  # patch '/artists/:id', to: 'artists#update'
  resources :artists
  resources :playlists, only: :index

  #cart
  patch '/cart/:song_id', to: 'cart#add_song', as: "cart"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  validates_presence_of :name

  has_many :songs
end

app/models/cart.rb
class Cart
  attr_reader :contents

  def initialize(contents)
    if contents
      @contents = contents
      @contents.default = 0
    else
      @contents = Hash.new(0)
    end
  end

  def add_song(song_id)
    @contents[song_id.to_s] += 1
  end

  def total
    @contents.values.sum
  end

  def song_count(song_id)
    @contents[song_id.to_s]
  end
end

app/models/playlist.rb
class Playlist < ApplicationRecord
  has_many :playlist_songs
  has_many :songs, through: :playlist_songs
end

app/models/playlist_song.rb
class PlaylistSong < ApplicationRecord
  belongs_to :playlist
  belongs_to :song
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :artist
  has_many :playlist_songs
  has_many :playlists, through: :playlist_songs
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :cart

  def cart
    @cart ||= Cart.new(session[:cart])
  end
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  def index
    @artists = Artist.all
  end

  def new
  end

  def create
    artist = Artist.new(artist_params)
    if artist.save
      redirect_to '/artists'
    else
      flash[:notice] = "Artist not created: Required information missing."
      render :new
    end
  end

  def edit
    @artist = Artist.find(params[:id])
  end

  def update
    artist = Artist.find(params[:id])
    artist.update(artist_params)
    redirect_to '/artists'
  end

  def destroy
    Artist.destroy(params[:id])
    redirect_to '/artists'
  end

  private

  def artist_params
    params.permit(:name)
  end
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  include ActionView::Helpers::TextHelper

  def add_song
    song = Song.find(params[:song_id])
    cart = Cart.new(session[:cart])
    cart.add_song(song.id)
    session[:cart] = cart.contents
    flash[:success] = "You now have #{pluralize(cart.song_count(song.id), 'copy')} of #{song.title} in your cart."
    redirect_to songs_path
  end
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  def index
    @playlists = Playlist.all
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def login
    user = User.find_by(username: params[:username])
    if user.authenticate(params[:password])
      session[:user_id] = user.id
      current_user
      redirect_to user_path(user)
    else
      render :new
    end
  end

  def logout
    session.delete(:user_id)
    redirect_to songs_path
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  def index
    @songs = Song.all
  end

  def show
    @song = Song.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def show
  end

  def create
    user = User.new(user_params)
    user.save
    flash[:message] = "Welcome, #{user.username}!"
    redirect_to songs_path
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/artists/edit.html.erb
<%= form_tag "/artists/#{@artist.id}", method: :patch do %>
  <%= label_tag :name %>
  <%= text_field_tag :name %>

  <%= submit_tag 'Update Artist' %>
<% end %>

app/views/artists/index.html.erb
<%= link_to 'New Artist', '/artists/new' %>

<% @artists.each do |artist| %>
  <h2><%= artist.name %></h2>
  <%= button_to 'Delete', "/artists/#{artist.id}", method: :delete %>
  <%= link_to 'Edit', "/artists/#{artist.id}/edit" %>
<% end %>

app/views/artists/new.html.erb
<%= form_tag '/artists' do %>
  <%= label_tag :name %>
  <%= text_field_tag :name %>

  <%= submit_tag 'Create Artist' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SetList</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"%>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <nav class="nav">
      <a class="nav-link active" href="/artists">Artists</a>
      <a class="nav-link active">Cart: <%= cart.total %></a>
    </nav>

    <% flash.each do |type, message| %>
      <p><%= message %></p>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/playlists/index.html.erb
<h1>Playlists!</h1>

<% @playlists.each do |playlist| %>
  <section id="playlist-<%= playlist.id %>">
    <h3><%= playlist.name %></h3>
    <p>Songs:</p>
    <ul>
      <% playlist.songs.each do |song| %>
        <li><%= song.title %></li>
      <% end %>
    </ul>
  </section>
<% end %>

app/views/playlists/new.html.erb
<%= form_for @playlist do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :songs %>
  <%= f.text_field :songs %>

  <%= f.submit %>
<% end %>

app/views/songs/index.html.erb
<h1>Songs</h1>
<p><%= flash[:success] %></p>
<% @songs.each do |song| %>
  <section id="song-<%= song.id %>" class="song">
    <h2><%= song.title %></h2>
    <p>Playcount: <%= song.play_count %></p>
    <%= button_to "Add Song", cart_path(song), method: :patch %>
  </section>
<% end %>

app/views/songs/new.html.erb
<%= form_for [@artist, @song] do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :length %>
  <%= f.text_field :length %>

  <%= f.label :play_count %>
  <%= f.text_field :play_count %>

  <%= f.submit %>
<% end %>

app/views/songs/show.html.erb
<h1><%= @song.title %></h1>
<p>By: <%= @song.artist.name %></p>

app/views/users/new.html.erb
<%= form_for @user do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username %>

  <%= f.label :password %>
  <%= f.text_field :password %>

  <%= f.submit %>
<% end %>

app/views/users/show.html.erb
<%= link_to 'Log out', logout_path %>

app/views/welcome/index.html.erb
<%= link_to 'Register as a User', new_user_path %>
<%= link_to 'I already have an account', login_path %>